version: '3'

includes:
  go:
    taskfile: ./examples/go/Taskfile.yaml
    dir: ./examples/go
  js:
    taskfile: ./examples/js/Taskfile.yaml
    dir: ./examples/js

tasks:
  default:
    cmds: [ "task -l" ]

  up:
    desc: "Start infrastructure (Redis)"
    cmds:
      - docker compose -f infra/docker-compose.yaml up -d
  down:
    desc: "Stop infrastructure"
    cmds:
      - docker compose -f infra/docker-compose.yaml down
