version: '3'

includes:
  usp:
    taskfile: ./usp/Taskfile.yaml
    dir: ./usp

  todo:
    taskfile: ./examples/todo-js/Taskfile.yaml
    dir: ./examples/todo-js

tasks:
  default:
    cmds: [ "task -l" ]

  up:
    desc: "A.1: Start infrastructure (Redis)"
    cmds:
      - docker compose -f infra/docker-compose.yaml up -d

  down:
    desc: "A.2: Stop infrastructure"
    cmds:
      - docker compose -f infra/docker-compose.yaml down
