version: '3'

includes:
  go:
    taskfile: ./prototypes/go/Taskfile.yaml
    dir: ./prototypes/go
  js:
    taskfile: ./prototypes/js/Taskfile.yaml
    dir: ./prototypes/js

tasks:
  default:
    cmds: [ "task -l" ]

  up:
    desc: "Start infrastructure (Redis)"
    cmds:
      - docker compose -f infra/docker-compose.yaml up -d
  down:
    desc: "Stop infrastructure"
    cmds:
      - docker compose -f infra/docker-compose.yaml down
