version: '3'

tasks:
  install:
    desc: "C.1: Install dependencies for todo-js example"
    cmds:
      - pnpm install

  start:
    desc: "C.2: Start todo-js example server"
    cmds:
      - pnpm start
