version: '3'

includes:
  js:
    taskfile: ./examples/js/Taskfile.yaml
    dir: ./examples/js
  nuxt:
    taskfile: ./examples/nuxt/Taskfile.yaml
    dir: ./examples/nuxt

tasks:
  default:
    cmds: [ "task -l" ]
